language: node_js
node_js:
 - "8"

jobs:
 include:
  - stage: test
    before_script: cd Frontend
    script:
     - npm install 
     - npm test
     - npm run build
  -
    before_script: cd Mobile
    script:
     - npm install
     - npm test

notifications:
 slack: innoprojectsummer2018:Me0KNpSZ1ES1OnWrwTUoD2Y7
