matrix:
  include:
    - language: node_js
      node_js:
       - "8"
      before_script:
        - cd Frontend
      script:
        - npm install
        - npm test
        - npm run build

    - language: android
      jdk: oraclejdk8
      android:
        components:
          - tools
          - android-25
          - build-tools-25.0.3
      before_install:
        - yes | sudo sdkmanager --licenses
      before_script:
        - cd Mobile
      script:
        - ./gradlew build connectedCheck

notifications:
 slack: innoprojectsummer2018:Me0KNpSZ1ES1OnWrwTUoD2Y7
